#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MyWeatherApplication.Resource", IsApplication=true)]

namespace MyWeatherApplication
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_horizontal_margin = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int activity_vertical_margin = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int margin_large = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int margin_small = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int margin_xlarge = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int margin_xsmall = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int txt_size_medium = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int txt_size_small = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int txt_size_xsmall = 2130968584;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int TimeSection = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int TimeText = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int condLabel = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int condSection = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int condText = 2131099652;
			
			// aapt resource value: 0x7f06000d
			public const int fragment_container = 2131099661;
			
			// aapt resource value: 0x7f060009
			public const int humidLabel = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int humidSection = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int humidText = 2131099658;
			
			// aapt resource value: 0x7f060019
			public const int humiditySection = 2131099673;
			
			// aapt resource value: 0x7f06000b
			public const int lv_daily_weather = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int lv_hourly_weather = 2131099660;
			
			// aapt resource value: 0x7f060016
			public const int maxTempSection = 2131099670;
			
			// aapt resource value: 0x7f060013
			public const int minTempSection = 2131099667;
			
			// aapt resource value: 0x7f060006
			public const int tempLabel = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int tempSection = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int tempText = 2131099655;
			
			// aapt resource value: 0x7f06001b
			public const int txt_Humidity = 2131099675;
			
			// aapt resource value: 0x7f06001a
			public const int txt_HumidityLabel = 2131099674;
			
			// aapt resource value: 0x7f060018
			public const int txt_MaxTemperature = 2131099672;
			
			// aapt resource value: 0x7f060017
			public const int txt_MaxTemperatureLabel = 2131099671;
			
			// aapt resource value: 0x7f060015
			public const int txt_MinTemperature = 2131099669;
			
			// aapt resource value: 0x7f060014
			public const int txt_MinTemperatureLabel = 2131099668;
			
			// aapt resource value: 0x7f060012
			public const int txt_Temperature = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int txt_TemperatureLabel = 2131099665;
			
			// aapt resource value: 0x7f06000e
			public const int txt_Time = 2131099662;
			
			// aapt resource value: 0x7f060010
			public const int txt_WeatherCondition = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int txt_WeatherConditionLabel = 2131099663;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CurrentWeather = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DailyWeather = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int HourlyWeather = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int WeatherListItem = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int CurrentWeather = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
